### ISSUE TITLE
Developer docs (e.g. overview of which classes map to which part in the editor)

### ISSUE THREAD

**Issue by jimkring** [ni/labview-icon-editor#14]
As mentioned [here](https://github.com/ni/labview-icon-editor/issues/13#issuecomment-2146096190) by @JayKayAce, it would be nice to have some developer documentation (e.g. about which classes map to which part in the editor and other aspects of code organization).

**Comment by svelderrainruiz** [comment]
Created Antidoc documentation on "\Antidoc-Output\Project-Documentation.html"
