### ISSUE TITLE
Add a new webhook to a Discord Channel

### ISSUE THREAD

**Issue by K-Bull** [ni/labview-icon-editor#18]
Hi, 

Someone with access to the github repository>Settings will need to add this webhook:
Payload URL:
https://discord.com/api/webhooks/1313531587467411548/aYnThtcbF-GIjXkTRkKPSOjSBOCddNuZ7y71RC2dRjOj6Qk58p79gZ-ss_7c7ZLWS0eu

Content type: application/json
"Send me everything"
Add Webhook

This is so we can get updates to this repository on LabVIEW Discord Channel.

Thanks,
K

**Comment by jimkring** [comment]
Thanks @K-Bull. I'll work with the team to get this integration set up.

**Comment by jimkring** [comment]
@gregr-ni will help get this set up tomorrow.

**Comment by K-Bull** [comment]
@gregr-ni  We have created a public channel for this now on LabVIEW Discord server.

could you please setup a webhook:

 repository>Settings>Webhooks
Payload URL: 
https://discord.com/api/webhooks/1313531587467411548/aYnThtcbF-GIjXkTRkKPSOjSBOCddNuZ7y71RC2dRjOj6Qk58p79gZ-ss_7c7ZLWS0eu 

with the following settings please
![image](https://github.com/user-attachments/assets/492fc41e-f703-4d79-88ce-1921a9c2186f)

**Comment by gregr-ni** [comment]
Done.

**Comment by gregr-ni** [comment]
Although it doesn't seem to be working.
![image](https://github.com/user-attachments/assets/500b8f0a-2b96-431a-bcc9-7b14482be66c)

**Comment by gregr-ni** [comment]
Had wrong content type. Maybe now.

**Comment by gregr-ni** [comment]
Nope. Still getting errors. @K-Bull, any ideas?

**Comment by K-Bull** [comment]
@gregr-ni , could I grab the screenshot after the content type is set to application/json?

**Comment by K-Bull** [comment]
https://discord.com/api/webhooks/1313531587467411548/aYnThtcbF-GIjXkTRkKPSOjSBOCddNuZ7y71RC2dRjOj6Qk58p79gZ-ss_7c7ZLWS0eu/github

I forgot to add the /github at the end of the link, if you can modify it as above please, it should work... ?

**Comment by gregr-ni** [comment]
Let's see now.

**Comment by gregr-ni** [comment]
Seems to be working.
![image](https://github.com/user-attachments/assets/6b113214-7fae-46c9-aea4-d93ec439d8f8)

**Comment by K-Bull** [comment]
Amazing thank you :)

**Comment by K-Bull** [comment]
Hey @gregr-ni, 
Upon review of "Send me everything", we think its a bit much. So could you please edit the webhook to "Let me select individual events" with the following enabled please:

Branch or tag creation
Discussions
Issues
Releases
Pull requests

Removed "Pushes" because I am not sure we would want to know every time someone commits. Pull requests events should tell us when things are being readied for release and releases are tag creation events

Thanks,
K

**Comment by gregr-ni** [comment]
Alright. Let's try that set.
