### ISSUE TITLE
Wanted: Handle underscores in filename when using "Set Icon to VI Name"

### ISSUE THREAD

**Issue by ShaneCravens** [ni/labview-icon-editor#22]
As mentioned above, if your filename has underscores instead of spaces, the "Set Icon to VI Name" is unusable. Would be great if it could treat an underscore the same as a space when parsing filename for the icon text.
![VI Name](https://github.com/user-attachments/assets/b4e541b8-3f4d-4d25-9779-0c34ef669718)

**Comment by JayKayAce** [comment]
I am pretty sure it would be an extension of the regular expression in here. 
![image](https://github.com/user-attachments/assets/30b66967-c5fa-4e34-a996-316f4459b4eb)

**Comment by elijah286** [comment]
Based on our team meeting this morning, @JayKayAce is going to comment further with his plans for how to create a test harness for this.

**Comment by JayKayAce** [comment]
Hey @elijah286 @gregr-ni
 I need some advice/feedback here
The affected VI is private to the Text-based VI Icon.lvlib. This makes it harder to write a unit test for. Is it possible to move the function to public functions instead or must it be private for something else to work properly?
This is the file
![image](https://github.com/user-attachments/assets/80cb985b-ee4c-4191-813b-e2ca51d7bf07)

Can you agree on making it public?

**Comment by gregr-ni** [comment]
I'd say make it community scope and add the test library as a friend.

**Comment by JayKayAce** [comment]
Pressing OK in the Friends menu gives a message that the Text-Based VI Icon.lvlib is locked
![image](https://github.com/user-attachments/assets/346a40ae-8d92-4c38-8a93-a0e895b90ef8)
and from my understanding of the help files, friendships are declared from the owner of the VI to another VI or library.
If I try to declare it the other way from the test lvlib -> Text-Based VI Icon.lvlib there is no message, but the friendship does not work for community scope.

**Comment by gregr-ni** [comment]
It is probably locked because some of its members are reserved. Make sure the icon editor is not loaded using "Tooling/Force Icon Editor to Unload.vi" then try again.

**Comment by JayKayAce** [comment]
Tried that but with the same result. I think the Icon editor is being reserved when loading the General properties for a library. As it seems to lock the LabVIEW Icon API.lvlib on loading the first page of library properties.

**Comment by JayKayAce** [comment]
It is possible to add the Test library friendship dependency outside LabVIEW. 

But another question came up. Would adding this friends relationship impact the finished product, where the Text-Based VI Icon.lvlib now expects the test library to be placed here:
./labview-icon-editor/Tooling/Unit tests/Text-Based VI Icon/Text-Based VI Icon Unit Tests.lvlib

**Comment by gregr-ni** [comment]
If you can get the syntax right, it should be fine to add that directly to the xml.

Listing a friend that is not always present should not be an issue.

**Comment by JayKayAce** [comment]
Opened PR https://github.com/ni/labview-icon-editor/pull/43 to merge to solve the issue.
