### ISSUE TITLE
Review changes to lvproj file related to unit tests PR

### ISSUE THREAD

**Issue by elijah286** [ni/labview-icon-editor#36]
This PR #35  was approved but merged the project file, so this needs to be evaluated to ensure it is still valid.

https://github.com/ni/labview-icon-editor/commit/8aee6bd10f412af5743b4bfab3570cba0f9307d6#diff-3a8751d03b79009bf8285cf88190e13f3d6e6fac0bf3715d2c12d11cde9e82c2

**Comment by gregr-ni** [comment]
Looks fine to me. Most changes are in dependencies which are recomputed on load anyway.

**Comment by gregr-ni** [comment]
Looks fine to me. Most changes are in dependencies which are recomputed on load anyway.
