### ISSUE TITLE
Increase icon resolution

### ISSUE THREAD

**Issue by svelderrainruiz** [ni/labview-icon-editor#44]
Refer to the post from the forums for more information about this [https://forums.ni.com/t5/LabVIEW-Idea-Exchange/Increase-Icon-Resolution/idi-p/4300624](url)

We need to identify which activities from that post can be transferred into specific unit testable action items that can be transformed into github issues.

**Comment by Flydroid** [comment]
This is an interesting improvement suggestion to LabVIEW in general. I can think of a few questions which would need to need do be solved (in order)? 

1. Do we know that LabVIEW can handle (and VIs can have) Icons larger than 32x32? Can a new 256x256  icon fit inside the screen space of the old icons? With labVIEWs pixel based UI everthing else also need to be scaled up?
2. Can it be backwards compatible - does scaling up all 32x32 Icons work? 
3. How would we create large 256x256 Icons? 32x32 is a accaptable amount of pixels to manipulate by hand. With larger Icons it becomes actual graphics design work. Maybe a text to image generator model trained on icons and glyphs?

**Comment by crossrulz** [comment]
@Flydroid hit my major issue with this: the rest of LabVIEW has to support a larger icon. Based on my understanding on current implementations, this will not work. Or will the idea be to be able to edit in a 256x256 pixel grid and it then gets scaled down to 32x32? That just seems very inefficient computationally and we, as users, will not get a WYSIWYG.
