### ISSUE TITLE
make text look normal on Linux

### ISSUE THREAD

**Issue by AntoineChalons** [ni/labview-icon-editor#47]
On Linux Desktop I have not found a way to have normal looking text from the icon editor

Icon made on Windows 
![image](https://github.com/user-attachments/assets/beee870e-c4b9-4d01-beeb-29b87c499063)

If I open it in Linux, the icon editor screws it up
![image](https://github.com/user-attachments/assets/5ccd40cf-6bdc-4e1c-bae2-96c46841349f)

**Comment by AntoineChalons** [comment]
I think this is a duplicate of #9

**Comment by jimkring** [comment]
Work in progress https://github.com/ni/labview-icon-editor/pull/433
